### ISSUE TITLE
Clarify maintenance

### ISSUE THREAD

**Issue by ThatsNoMoon** [tailhook/quick-error#55]
It seems like `quick_error` has fallen behind on modern rust idioms. Are you planning on updating this crate further? Maybe it would be prudent to suggest a more modern and maintained alternative like [`thiserror`](https://github.com/dtolnay/thiserror) in the readme if not. Otherwise, issues like #42 and #48 are blockers for some users, myself included.

**Comment by tailhook** [comment]
Well, the point why people still use `quick_error` is for avoiding procedural macros (perhaps because procedural macros makes much longer to compile on cold cache), so #42 doesn't make sense. #48 probably can be fixed (I think it was a problem at the moment the issue was created as there was no `vis` qualifier). I'm not sure if fixing #48 requires bumping minimal supported rust version, though.

**Comment by ThatsNoMoon** [comment]
That's reasonable.

> I'm not sure if fixing #48 requires bumping minimal supported rust version, though.

If `quick-error` has a documented MSRV, it's not very discoverable. `vis` was added over 2 years ago, in Rust 1.30. It's unclear to me if that is more or less than what you want to support.

**Comment by tailhook** [comment]
> If `quick-error` has a documented MSRV, it's not very discoverable. `vis` was added over 2 years ago, in Rust 1.30. It's unclear to me if that is more or less than what you want to support.

It's definitely >= 1.31 (first edition 2018) now. But yes, has to be more discoverable.
